ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ id.nearyou.app.ApplicationKt.module ]
    }
    environment = "production"
    environment = ${?KTOR_ENV}
}
