import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id("nearyou.kotlin.multiplatform")
    alias(libs.plugins.androidLibrary)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    kotlin("native.cocoapods")
}

// mobile-admob-ads-foundation: the mobile (KMP: Android + iOS) Google Mobile Ads + UMP ad-serving seam.
// This is the ONLY module permitted to import the Google Mobile Ads / UMP SDKs (CLAUDE.md invariant #16 —
// no vendor SDK import outside :infra:*). It exposes the vendor-FREE `AdProvider` interface + plain-Kotlin
// domain models (`NativeAdContent` / `ConsentState` / `AdRequestMode`) in commonMain, plus the platform
// native-ad rendering surface (`NativeAdSurface`, an expect/actual @Composable drawing the platform
// `NativeAdView` (Android) / `GADNativeAdView` (iOS) so impressions/clicks register per AdMob policy,
// design D2). The single Google SDK implementation (`AndroidAdProvider` / `IosAdProvider`) lands alongside
// the SDK dependency here; :mobile:app depends on this module for the interface + composable only, with the
// vendor dep `implementation`-scoped so it never reaches the app's compile classpath. Mirrors the §2.6
// realtime/revenuecat seam, EXCEPT the iOS binding is generated by the KMP `native.cocoapods` plugin from
// the Ads/UMP Pods (Google publishes no KMP Ads SDK — the GoogleSignIn-pod precedent; design D7), so this
// module is Compose-enabled (the platform native-ad view interop) and applies the cocoapods plugin.
kotlin {
    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }

    iosArm64()
    iosSimulatorArm64()

    cocoapods {
        version = "1.0"
        summary = "NearYou :infra:admob — Google Mobile Ads + UMP cinterop seam"
        homepage = "https://nearyou.id"
        ios.deploymentTarget = "16.0"
        framework {
            baseName = "infraAdmob"
            isStatic = true
        }
        // Declare the Ads + UMP Pods WITHOUT linkOnly so the cocoapods plugin GENERATES the cinterop
        // bindings the iosMain actual consumes (Google publishes no KMP Ads SDK — the GoogleSignIn-pod
        // precedent; design D7). :mobile:app re-declares the same Pods `linkOnly = true` so the final
        // ComposeApp framework links the binaries (the Sentry/RevenueCat linkOnly precedent). -fmodules is
        // required by the Pods' modular headers. Versions pinned in libs.versions.toml.
        pod("Google-Mobile-Ads-SDK") {
            // The pod is `Google-Mobile-Ads-SDK` but the clang module it vends is `GoogleMobileAds` —
            // cinterop @imports the module name; without this it generates EMPTY bindings (all GAD* refs
            // unresolved). The Kotlin package stays pod-based (`cocoapods.Google_Mobile_Ads_SDK`).
            moduleName = "GoogleMobileAds"
            version = libs.versions.googleMobileAdsIos.get()
            extraOpts += listOf("-compiler-option", "-fmodules")
        }
        pod("GoogleUserMessagingPlatform") {
            // The pod is `GoogleUserMessagingPlatform` but the framework/clang module it vends is
            // `UserMessagingPlatform` — cinterop @imports the module name, not the pod name.
            moduleName = "UserMessagingPlatform"
            version = libs.versions.googleUmpIos.get()
            extraOpts += listOf("-compiler-option", "-fmodules")
        }
    }

    sourceSets {
        commonMain.dependencies {
            implementation(libs.kotlinx.coroutines.core)
            // Compose runtime/foundation/ui for the platform native-ad rendering surface (AndroidView /
            // UIKitView interop). The model + interface carry NO vendor type; only the rendering actuals do.
            implementation(libs.compose.runtime)
            implementation(libs.compose.foundation)
            implementation(libs.compose.ui)
        }
        androidMain.dependencies {
            // Google Mobile Ads + UMP SDK — the ONLY place these vendor SDKs are imported (invariant #16).
            // `implementation`-scoped so they never reach :mobile:app's compile classpath; the app consumes
            // only the vendor-free AdProvider interface + NativeAdContent.
            implementation(libs.google.playServicesAds)
            implementation(libs.google.userMessagingPlatform)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutines.test)
        }
    }
}

android {
    namespace = "id.nearyou.app.infra.admob"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    defaultConfig {
        minSdk = libs.versions.android.minSdk.get().toInt()
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}
