#!/usr/bin/env bash
# setup_dev_env.sh: create dev/.env (gitignored) from dev/.env.example with
# freshly generated throwaway secrets, so the backend boots exactly the way the
# dev/README.md laptop flow does:
#
#   set -a; . dev/.env; set +a
#   ./gradlew --no-daemon :backend:ktor:run          # serves :8080
#
# Runs automatically from scripts/session_start.sh in a cloud session; safe to
# run by hand anywhere.
#
# - NEVER overwrites an existing dev/.env (a developer's hand-tuned file wins).
#   Delete it first to regenerate.
# - Every generated value is random, local to this machine, and not a real
#   credential (no Secret Manager slot is read or written).
# - KTOR_ENV defaults to `test`: boots with no Firebase / OpenAI / Supabase
#   service-role secrets (see the KTOR_ENV note in dev/.env.example). Override
#   with DEV_ENV_KTOR_ENV=development once those secrets are exported.
# - Also appends the two admin-panel keys (read lazily at /admin/login, not at
#   boot), so the verify-loop §A admin bootstrap works without extra steps:
#   pass ADMIN_TOTP_AES_KEY_BASE64="$ADMIN_TOTP_SECRET_AES_KEY" to the bootstrap.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$REPO_ROOT/dev/.env.example"
DST="$REPO_ROOT/dev/.env"

log() { printf '\033[1;36m[dev-env]\033[0m %s\n' "$*"; }
die() { printf '\033[1;31m[dev-env]\033[0m %s\n' "$*" >&2; exit 1; }

if [[ -f "$DST" ]]; then
  log "dev/.env already exists, leaving it untouched."
  exit 0
fi
[[ -f "$SRC" ]] || die "dev/.env.example not found."
command -v openssl >/dev/null 2>&1 || die "openssl not found."

# KTOR_RSA_PRIVATE_KEY + INVITE_CODE_SECRET + JITTER_SECRET, one KEY=VALUE per
# line, the same generator the dev/README.md first-time setup uses.
generated="$(sh "$REPO_ROOT/dev/scripts/generate-rsa-keypair.sh")"
value_of() { printf '%s\n' "$generated" | sed -n "s/^$1=//p"; }

export GEN_KTOR_ENV="${DEV_ENV_KTOR_ENV:-test}"
export GEN_KTOR_RSA_PRIVATE_KEY; GEN_KTOR_RSA_PRIVATE_KEY="$(value_of KTOR_RSA_PRIVATE_KEY)"
export GEN_INVITE_CODE_SECRET; GEN_INVITE_CODE_SECRET="$(value_of INVITE_CODE_SECRET)"
export GEN_JITTER_SECRET; GEN_JITTER_SECRET="$(value_of JITTER_SECRET)"
export GEN_SUPABASE_JWT_SECRET; GEN_SUPABASE_JWT_SECRET="$(openssl rand -base64 32 | tr -d '\n')"
for k in KTOR_RSA_PRIVATE_KEY INVITE_CODE_SECRET JITTER_SECRET; do
  v="GEN_$k"; [[ -n "${!v}" ]] || die "generate-rsa-keypair.sh did not emit $k."
done

umask 077
tmp="$(mktemp "$REPO_ROOT/dev/.env.XXXXXX")"
trap 'rm -f "$tmp"' EXIT

# Fill the matching KEY= lines of the example (awk + ENVIRON, not sed: base64
# values carry `/`, `+`, `=`). Every other line, comments included, is kept.
awk '
  /^(KTOR_ENV|KTOR_RSA_PRIVATE_KEY|SUPABASE_JWT_SECRET|INVITE_CODE_SECRET|JITTER_SECRET)=/ {
    key = substr($0, 1, index($0, "=") - 1)
    print key "=" ENVIRON["GEN_" key]
    next
  }
  { print }
' "$SRC" > "$tmp"

{
  echo
  echo "# Admin panel (lazy: read at /admin/login, not at boot). Generated by"
  echo "# scripts/setup_dev_env.sh: base64 of 32 random bytes each."
  echo "ADMIN_TOTP_SECRET_AES_KEY=$(openssl rand -base64 32 | tr -d '\n')"
  echo "ADMIN_CSRF_HMAC_KEY=$(openssl rand -base64 32 | tr -d '\n')"
} >> "$tmp"

mv "$tmp" "$DST"
trap - EXIT
log "Wrote dev/.env (KTOR_ENV=$GEN_KTOR_ENV, fresh throwaway secrets)."
